const CONFIG={webAppUrl: "https://script.google.com/macros/s/AKfycbxAqDrnMji9a0X2y5aEKbaDuan5qzElhnZokdKeYHjpl4TKcUWZ4WJsw0VC6GpLsSJk/exec",storageKey:"agropec_ebook_v2"};
const screens=[...document.querySelectorAll('.screen')];const answers={};let current=0;window.dataLayer=window.dataLayer||[];
function event(name,data={}){dataLayer.push({event:name,...data});if(typeof gtag==='function')gtag('event',name,data);if(typeof fbq==='function'){const standard={ebook_lead:'Lead',whatsapp_open:'Contact'}[name];standard?fbq('track',standard,data):fbq('trackCustom',name,data)}}
function show(i){current=Math.max(0,Math.min(i,screens.length-1));screens.forEach((s,n)=>s.classList.toggle('active',n===current));const pct=current===0?0:Math.min(100,Math.round((current/6)*100));document.getElementById('progressBar').style.width=pct+'%';window.scrollTo({top:0,behavior:'smooth'});if(current>0&&current<7)event('ebook_step_view',{step:current})}
function save(){localStorage.setItem(CONFIG.storageKey,JSON.stringify(answers))}
function phone(v){let d=String(v||'').replace(/\D/g,'');if(d.startsWith('55'))return d;if(d.length===10||d.length===11)return '55'+d;return d}
document.getElementById('startBtn').onclick=()=>{event('begin_ebook_form');show(1)};
document.querySelectorAll('.question').forEach(section=>{const key=section.dataset.key;section.querySelectorAll('.options button').forEach(btn=>btn.onclick=()=>{section.querySelectorAll('.options button').forEach(b=>b.classList.remove('selected'));btn.classList.add('selected');answers[key]=btn.dataset.value;save()});section.querySelector('.next').onclick=()=>{if(!answers[key]){alert('Selecione uma opção para continuar.');return}event('ebook_answer',{question:key,answer:answers[key]});show(current+1)}});
document.querySelectorAll('.back').forEach(b=>b.onclick=()=>show(current-1));
document.getElementById('locationNext').onclick=()=>{const cidade=document.getElementById('cidade').value.trim(),estado=document.getElementById('estado').value;if(!cidade||!estado){document.getElementById('locationError').textContent='Informe a cidade e o estado.';return}answers.cidade=cidade;answers.estado=estado;save();event('ebook_answer',{question:'localizacao'});show(current+1)};
document.getElementById('whatsapp').addEventListener('input',e=>{let d=e.target.value.replace(/\D/g,'').slice(0,11);e.target.value=d.length>10?d.replace(/(\d{2})(\d{5})(\d{0,4})/,'($1) $2-$3'):d.replace(/(\d{2})(\d{4})(\d{0,4})/,'($1) $2-$3')});
document.getElementById('submitBtn').onclick=async()=>{const btn=document.getElementById('submitBtn'),err=document.getElementById('contactError');err.textContent='';const nome=document.getElementById('nome').value.trim(),whatsapp=phone(document.getElementById('whatsapp').value),consent=document.getElementById('consentimento').checked;if(!nome){err.textContent='Informe seu nome.';return}if(whatsapp.length<12||whatsapp.length>13){err.textContent='Informe um WhatsApp válido com DDD.';return}if(!consent){err.textContent='É necessário autorizar o envio pelo WhatsApp.';return}const q=new URLSearchParams(location.search);const payload={...answers,nome,whatsapp,consentimento:true,origem:'Ebook Sal Proteinado',utm_source:q.get('utm_source')||'',utm_medium:q.get('utm_medium')||'',utm_campaign:q.get('utm_campaign')||'',utm_content:q.get('utm_content')||'',fbclid:q.get('fbclid')||'',pagina:location.href};btn.disabled=true;btn.textContent='ENVIANDO SEU GUIA...';try{const r=await fetch(CONFIG.webAppUrl,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(payload)});const data=await r.json();if(!data.sucesso)throw new Error(data.mensagem||'Falha ao enviar.');event('ebook_lead',{lead_score:data.score||0,classification:data.classificacao||''});localStorage.removeItem(CONFIG.storageKey);document.getElementById('leadId').textContent=data.id_lead?'Protocolo: '+data.id_lead:'';document.getElementById('openWhatsapp').href='https://wa.me/'+whatsapp;show(7)}catch(e){document.getElementById('fatalError').textContent=e.message;show(8)}finally{btn.disabled=false;btn.textContent='RECEBER MEU GUIA GRÁTIS'}};
event('ebook_offer_view');
